# Check pre-requisites
- include: pre-requisites.yml

# Commissioning block
- name: "AWS | VPC | Provision the VPC and subnets"
  local_action:
    module: ec2_vpc
    region: "{{ vpc_region }}"
    state: "present"
    cidr_block: "{{ vpc_cidr_block }}"
    resource_tags: "{{ vpc_resource_tags }}"
    subnets: "{{ vpc_subnets }}"
    internet_gateway: "{{ vpc_internet_gateway }}"
    route_tables: "{{ public_subnet_routes }}"
  register: vpc

- debug: var=vpc verbosity=4

# Decommission block
- block:
  - name: "AWS | VPC | Decommission the VPC and subnets"
    local_action:
      module: ec2_vpc
      region: "{{ vpc_region }}"
      state: "absent"
      cidr_block: "{{ vpc_cidr_block }}"
      resource_tags: "{{ vpc_resource_tags }}"
      subnets: "{{ vpc_subnets }}"
      internet_gateway: "{{ vpc_internet_gateway }}"
      route_tables: "{{ public_subnet_routes }}"

  when: vpc_state == "absent"