---
- name: Website | Provision networking | AWS | EC2 | Security | Create Inbound Security Groups
  local_action:
    module: ec2_group
    name: "{{ item.sg_name }}"
    description: "{{ item.sg_description }}"
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    state: present
    rules: "{{ item.sg_rules }}"
  with_items: inbound_security_groups
  register: inbound_sg

- name: Website | Provision networking | AWS | EC2 | Security | Create Outbound Security Groups
  local_action:
    module: ec2_group
    name: "{{ item.sg_name }}"
    description: "{{ item.sg_description }}"
    region: "{{ vpc_region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    state: present
    rules_egress: "{{ item.sg_rules }}"
  with_items: outbound_security_groups
  register: outbound_sg

- name: Website | Provision networking | AWS | EC2 | Security | Tag Security Groups
  local_action:
    module: ec2_tag
    resource: "{{ item.group_id}}"
    region: "{{ vpc_region }}"
    state: present
    tags:
      Name: "{{ vpc_name }}-{{ item.item.sg_name }}"
  with_items:
    - "{{ inbound_sg.results }}"
    - "{{ outbound_sg.results }}"