---
# Name of the SSH key registered in IAM
key_name: "{{ ssh_key_name }}"

# AWS EC2 image ID, this image should be a *unix image with the ECS Agent already installed
ec2_ami_id: ami-76e95b05

# EC2 instance type for all instances created during auto scaling
ec2_instance_type: t2.medium

# Name to be applied to any EC2 instances
ec2_instance_name: ecs_host

# Initial number of EC2 instances to auto scale
cms_ec2_asg_desired_capacity: 4

# Maximum number of EC2 instances to auto scale
cms_ec2_asg_max_size: 8

# Tags to apply to all EC2 instances created during auto scaling
ec2_tags:
  - component: "{{ ec2_instance_name }}"
    Name: "{{ vpc_name }}-{{ ec2_instance_name }}"
    env: "{{ env }}"