---
#
# Variables that define defaults for RDS management, not the username and password for the database are not stored
# here, they must be passed in as command line arguments:
#
# - contentstore_database_username
# - contentstore_database_password
#
# Alternatively defaults can be set in a encrypted file using ansible-vault
#

# Name of the DB instance
contentstore_database_instance_name: "{{ cms_vpc_name }}-cstore"

# Database size in GB (min size for RDS is 5GB)
contentstore_database_size: 5

# Instance type
contentstore_database_instance_type: db.t2.medium

# Name to give to the group of subnets reserved in your VPC for RDS
contentstore_subnet_groupname: "{{ cms_vpc_name }}-cstore"

# DB engine type, e.g. MySQL
db_engine: MySQL