---
#
# Variables for VPC
#
cms_vpc_name: "{{ application }}-{{ env }}"
cms_vpc_region: "{{ region }}"
cms_vpc_cidr_block: "172.40.0.0/16"

# Subnets for ECS cluster (2 AZs)
subnet_ecscluster_cidr_block_1: "172.40.10.0/24"
subnet_ecscluster_az_1: "{{ cms_vpc_region }}a"

subnet_ecscluster_cidr_block_2: "172.40.20.0/24"
subnet_ecscluster_az_2: "{{ cms_vpc_region }}b"

# Subnets for "Content Store", e.g. RDS (2 AZs)
subnet_contentstore_cidr_block_1: "172.40.50.0/24"
subnet_contentstore_az_1: "{{ cms_vpc_region }}a"

subnet_contentstore_cidr_block_2: "172.40.60.0/24"
subnet_contentstore_az_2: "{{ cms_vpc_region }}b"

#
# Subnets definitions for the VPC
#
# *** DO NOT CHANGE ORDER WITHOUT UPDATING ORDERING ASSUMPTIONS IN PLAYBOOK ***
#
cms_vpc_subnets:
 - cidr: "{{ subnet_ecscluster_cidr_block_1 }}"
   az: "{{ subnet_ecscluster_az_1 }}"
   resource_tags: {
    "Name": "{{ cms_vpc_name }}-ecscluster-{{ subnet_ecscluster_az_1 }}",
    "env": "{{ env }}",
    "application": "{{ application }}"
    }

 - cidr: "{{ subnet_ecscluster_cidr_block_2 }}"
   az: "{{ subnet_ecscluster_az_2 }}"
   resource_tags: {
    "Name":"{{ cms_vpc_name }}-ecscluster-{{ subnet_ecscluster_az_2 }}",
    "env": "{{ env }}",
    "application": "{{ application }}"
    }

 - cidr: "{{ subnet_contentstore_cidr_block_1 }}"
   az: "{{ subnet_contentstore_az_1 }}"
   resource_tags: {
    "Name":"{{ cms_vpc_name }}-contentstore-{{ subnet_contentstore_az_1 }}",
    "env": "{{ env }}",
    "application": "{{ application }}"
    }

 - cidr: "{{ subnet_contentstore_cidr_block_2 }}"
   az: "{{ subnet_contentstore_az_2 }}"
   resource_tags: {
    "Name":"{{ cms_vpc_name }}-contentstore-{{ subnet_contentstore_az_2 }}",
    "env": "{{ env }}",
    "application": "{{ application }}"
    }

#
# Routing tables for subnets which require access to the Internet
#
cms_public_subnet_routes:
 - subnets:
     - "{{ subnet_ecscluster_cidr_block_1 }}"
     - "{{ subnet_ecscluster_cidr_block_2 }}"
   routes:
     - dest: 0.0.0.0/0
       gw: igw